# Lab | Pandas

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

The data includes information such as customer ID, state, gender, education, income, and other variables that can be used to perform various analyses.

Throughout the lab, we will be using the pandas library in Python to manipulate and analyze the data. Pandas is a powerful library that provides various data manipulation and analysis tools, including the ability to load and manipulate data from a variety of sources, including CSV files.

### Data Description

- Customer - Customer ID

- ST - State where customers live

- Gender - Gender of the customer

- Education - Background education of customers 

- Customer Lifetime Value - Customer lifetime value(CLV) is the total revenue the client will derive from their entire relationship with a customer. In other words, is the predicted or calculated value of a customer over their entire duration as a policyholder with the insurance company. It is an estimation of the net profit that the insurance company expects to generate from a customer throughout their relationship with the company. Customer Lifetime Value takes into account factors such as the duration of the customer's policy, premium payments, claim history, renewal likelihood, and potential additional services or products the customer may purchase. It helps insurers assess the long-term profitability and value associated with retaining a particular customer.

- Income - Customers income

- Monthly Premium Auto - Amount of money the customer pays on a monthly basis as a premium for their auto insurance coverage. It represents the recurring cost that the insured person must pay to maintain their insurance policy and receive coverage for potential damages, accidents, or other covered events related to their vehicle.

- Number of Open Complaints - Number of complaints the customer opened

- Policy Type - There are three type of policies in car insurance (Corporate Auto, Personal Auto, and Special Auto)

- Vehicle Class - Type of vehicle classes that customers have Two-Door Car, Four-Door Car SUV, Luxury SUV, Sports Car, and Luxury Car

- Total Claim Amount - the sum of all claims made by the customer. It represents the total monetary value of all approved claims for incidents such as accidents, theft, vandalism, or other covered events.

External Resources: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

## Challenge 1: Understanding the data

In this challenge, you will use pandas to explore a given dataset. Your task is to gain a deep understanding of the data by analyzing its characteristics, dimensions, and statistical properties.

- Identify the dimensions of the dataset by determining the number of rows and columns it contains.
- Determine the data types of each column and evaluate whether they are appropriate for the nature of the variable. You should also provide suggestions for fixing any incorrect data types.
- Identify the number of unique values for each column and determine which columns appear to be categorical. You should also describe the unique values of each categorical column and the range of values for numerical columns, and give your insights.
- Compute summary statistics such as mean, median, mode, standard deviation, and quartiles to understand the central tendency and distribution of the data for numerical columns. You should also provide your conclusions based on these summary statistics.
- Compute summary statistics for categorical columns and providing your conclusions based on these statistics.

In [90]:
import pandas as pd
url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"
df = pd.read_csv(url)
df.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [91]:


def identify_dimensiones(dataframe_original):
    filas,columnas  = dataframe_original.shape
    return filas,columnas

def print_dimensiones(dataframe_original):
    filas, columnas = identify_dimensiones(dataframe_original)
    print(f"El DataFrame tiene {filas} filas y {columnas} columnas.")

def view_types_columns(dataframe_original):
    dtypes_dataframe = dataframe_original.dtypes
    return dtypes_dataframe

def print_types_columns (dataframe_original):
    for col, type_col in df.dtypes.items():
        print(f"The column: {col} is type: {type_col}")

def select_correct_type():
    cambios_propuestos = []
    mas_cambios = "yes"

    while mas_cambios == "yes":
        cambio = input("Pon los cambios que harías:\n")
        cambios_propuestos.append(cambio)

        mas_cambios = input("¿Deseas algún cambio más? Yes/No:\n").strip().lower()

    return cambios_propuestos


def print_cambios_propuestos(cambios_propuestos):
    print("\nCambios propuestos:")
    for c in cambios_propuestos:
        print(f"- {c}")


def seleccionar_valores_unicos(df):
    unique_valors = df.nunique()
    return unique_valors

def print_valores_uniques (unique_values):
    print(unique_values)


def seleccionar_valores_statistics(df):
    object_columns = df.select_dtypes(include=['object', 'string']).columns.tolist()
    numeric_columns = df.select_dtypes(include='number').columns.tolist()
    return object_columns, numeric_columns


def print_valores_statistics(numeric_column,object_columns):
    print(f"Valores categoricos {object_columns}")
    print(f"Valores numericos {numeric_column}")

def print_summary_statics(df):
    print(df.describe())
    
def print_categorical_statics(df):
    print(df.describe(include= ['object', 'string']))


def print_conclusions_summary():
    print(input(f"Conclusions about summary_statitics"))        
    

def print_conclusions_categorical():
        print(input(f"Conclusions about categorical_statitics"))

In [92]:
  
print("-------------------- SALIDAS ----------------------------------------------------------------")

filas_df, columnas_df = identify_dimensiones(df)
print_dimensiones(df)

-------------------- SALIDAS ----------------------------------------------------------------
El DataFrame tiene 4008 filas y 11 columnas.

In [93]:
types_columns = view_types_columns(df)
print_types_columns(df)

The column: Customer is type: str
The column: ST is type: str
The column: GENDER is type: str
The column: Education is type: str
The column: Customer Lifetime Value is type: str
The column: Income is type: float64
The column: Monthly Premium Auto is type: float64
The column: Number of Open Complaints is type: str
The column: Policy Type is type: str
The column: Vehicle Class is type: str
The column: Total Claim Amount is type: float64

In [ ]:
cambios_propuestos = select_correct_type() #"Pasar number of Complaints a integuer y Customer life a float que es dinero"

In [176]:
print_cambios_propuestos(cambios_propuestos)

Cambios propuestos:
- "Pasar number of Complaints a integuer y Customer life a float que es dinero"

In [96]:
valores_unicos = seleccionar_valores_unicos(df)
print(valores_unicos)

Customer                     1071
ST                              8
GENDER                          5
Education                       6
Customer Lifetime Value      1027
Income                        774
Monthly Premium Auto          132
Number of Open Complaints       6
Policy Type                     3
Vehicle Class                   6
Total Claim Amount            761
dtype: int64

In [177]:
object_columns, numeric_columns  = seleccionar_valores_statistics(df)
print_valores_statistics(numeric_columns,object_columns)

Valores categoricos ['Customer', 'ST', 'GENDER', 'Education', 'Customer Lifetime Value', 'Number of Open Complaints', 'Policy Type', 'Vehicle Class']
Valores numericos ['Income', 'Monthly Premium Auto', 'Total Claim Amount']

In [178]:

print_summary_statics(df)

             Income  Monthly Premium Auto  Total Claim Amount
count   1071.000000           1071.000000         1071.000000
mean   39295.701214            193.234360          404.986909
std    30469.427060           1601.190369          293.027260
min        0.000000             61.000000            0.382107
25%    14072.000000             68.000000          202.157702
50%    36234.000000             83.000000          354.729129
75%    64631.000000            109.500000          532.800000
max    99960.000000          35354.000000         2893.239678

In [99]:
print_categorical_statics(df)

       Customer      ST GENDER Education Customer Lifetime Value  \
count      1071    1071    954      1071                    1068
unique     1071       8      5         6                    1027
top     RB50392  Oregon      F  Bachelor              445811.34%
freq          1     320    457       324                       4

       Number of Open Complaints    Policy Type  Vehicle Class
count                       1071           1071           1071
unique                         6              3              6
top                       1/0/00  Personal Auto  Four-Door Car
freq                         830            780            576

In [100]:
print_conclusions_summary()
"""  Valor minimo es cero ...hay algun dato sin cubrir... 
la media 40000 quiero un sueldo asi
hay un seguro de 61 y otro de 35000??                            
reclamacion de 0,38 vale mas el sobre que lo reclamado"""

"""  Valor minimo es cero ...hay algun dato sin cubrir...  la media 40000 quiero un sueldo asi hay un seguro de 61 y otro de 35000??                             reclamacion de 0,38 vale mas el sobre que lo reclamado"""

'  Valor minimo es cero ...hay algun dato sin cubrir... \nla media 40000 quiero un sueldo asi\nhay un seguro de 61 y otro de 35000??                            \nreclamacion de 0,38 vale mas el sobre que lo reclamado'

In [102]:

print_conclusions_categorical()
""" hay una burrada en el top 445811 con un 445811 % que debe estar mal
hay una fecha o similar 1/0/00 """

""" hay una burrada en el top 445811 con un 445811 % que debe estar mal hay una fecha o similar 1/0/00 """

' hay una burrada en el top 445811 con un 445811 % que debe estar mal\nhay una fecha o similar 1/0/00 '

## Challenge 2: analyzing the data

### Exercise 1

The marketing team wants to know the top 5 less common customer locations. Create a pandas Series object that contains the customer locations and their frequencies, and then retrieve the top 5 less common locations in ascending order.

In [112]:
import pandas as pd
url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"
df = pd.read_csv(url)
df.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [ ]:
def extract_names_columns(df):
    columnas = df.columns.tolist() #para ver las columnas
    for col in columnas:
        print(col)
    return columnas

In [ ]:
columnas = extract_names_columns(df)

Customer
ST
GENDER
Education
Customer Lifetime Value
Income
Monthly Premium Auto
Number of Open Complaints
Policy Type
Vehicle Class
Total Claim Amount

In [160]:
def extract_columns_ordered(df,column,number):
    ordered_column =  df[column].sort_values(ascending=True).head(number) # para ponerlas ordenadas 
    return ordered_column

In [161]:
extract_columns_ordered(df,'Customer',2)

948    AA71604
184    AB13432
Name: Customer, dtype: str

### Exercise 2

The sales team wants to know the total number of policies sold for each type of policy. Create a pandas Series object that contains the policy types and their total number of policies sold, and then retrieve the policy type with the highest number of policies sold.

*Hint:*
- *Using value_counts() method simplifies this analysis.*
- *Futhermore, there is a method that returns the index of the maximum value in a column or row.*

In [175]:
import pandas as pd
url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"
df = pd.read_csv(url)
df.head()
df.describe(include= "all")

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
count,1071,1071,954,1071,1068,1071.000000,1071.000000,1071,1071,1071,1071.000000
unique,1071,8,5,6,1027,NaN,NaN,6,3,6,NaN
top,RB50392,Oregon,F,Bachelor,445811.34%,NaN,NaN,1/0/00,Personal Auto,Four-Door Car,NaN
freq,1,320,457,324,4,NaN,NaN,830,780,576,NaN
mean,NaN,NaN,NaN,NaN,NaN,39295.701214,193.234360,NaN,NaN,NaN,404.986909
std,NaN,NaN,NaN,NaN,NaN,30469.427060,1601.190369,NaN,NaN,NaN,293.027260
min,NaN,NaN,NaN,NaN,NaN,0.000000,61.000000,NaN,NaN,NaN,0.382107
25%,NaN,NaN,NaN,NaN,NaN,14072.000000,68.000000,NaN,NaN,NaN,202.157702
50%,NaN,NaN,NaN,NaN,NaN,36234.000000,83.000000,NaN,NaN,NaN,354.729129
75%,NaN,NaN,NaN,NaN,NaN,64631.000000,109.500000,NaN,NaN,NaN,532.800000
max,NaN,NaN,NaN,NaN,NaN,99960.000000,35354.000000,NaN,NaN,NaN,2893.239678

In [163]:
def extract_names_columns(df):
    columnas = df.columns.tolist() #para ver las columnas
    for col in columnas:
        print(col)
    return columnas

In [171]:
def count_values_column(df, column):
       count_values_in_column = df[column].value_counts()
       print(count_values_in_column)
       return count_values_in_column

In [ ]:
def highest_value_of_column(df, column, number):
    return df[column].value_counts().head(number)

Policy Type
Personal Auto    780
Name: count, dtype: int64

In [164]:
columnas = extract_names_columns(df)

Customer
ST
GENDER
Education
Customer Lifetime Value
Income
Monthly Premium Auto
Number of Open Complaints
Policy Type
Vehicle Class
Total Claim Amount

In [172]:
count_values_column(df,'Policy Type')

Policy Type
Personal Auto     780
Corporate Auto    234
Special Auto       57
Name: count, dtype: int64

Policy Type
Personal Auto     780
Corporate Auto    234
Special Auto       57
Name: count, dtype: int64

In [ ]:
resultado = highest_value_of_column(df, "Policy Type",1)
print(resultado)

### Exercise 3

The sales team wants to know if customers with Personal Auto have a lower income than those with Corporate Auto. How does the average income compare between the two policy types?

- Use *loc* to create two dataframes: one containing only Personal Auto policies and one containing only Corporate Auto policies.
- Calculate the average income for each policy.
- Print the results.

In [188]:
import pandas as pd
url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"
df = pd.read_csv(url)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   1071 non-null   str
 1   ST                         1071 non-null   str
 2   GENDER                     954 non-null    str
 3   Education                  1071 non-null   str
 4   Customer Lifetime Value    1068 non-null   str
 5   Income                     1071 non-null   float64
 6   Monthly Premium Auto       1071 non-null   float64
 7   Number of Open Complaints  1071 non-null   str
 8   Policy Type                1071 non-null   str
 9   Vehicle Class              1071 non-null   str
 10  Total Claim Amount         1071 non-null   float64
dtypes: float64(3), str(8)
memory usage: 344.6 KB

In [197]:
df_personal_auto = df.loc[df['Policy Type'] == "Personal Auto"]

df_personal_auto

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
5,OC83172,Oregon,F,Bachelor,825629.78%,62902.0,69.0,1/0/00,Personal Auto,Two-Door Car,159.383042
...,...,...,...,...,...,...,...,...,...,...,...
1065,XD85577,Cali,M,Bachelor,284226.69%,69417.0,73.0,1/1/00,Personal Auto,Four-Door Car,30.874869
1066,TM65736,Oregon,M,Master,305955.03%,38644.0,78.0,1/1/00,Personal Auto,Four-Door Car,361.455219
1067,VJ51327,Cali,F,High School or Below,2031499.76%,63209.0,102.0,1/2/00,Personal Auto,SUV,207.320041
1068,GS98873,Arizona,F,Bachelor,323912.47%,16061.0,88.0,1/0/00,Personal Auto,Four-Door Car,633.600000
1070,MY31220,California,F,College,899704.02%,54230.0,112.0,1/0/00,Personal Auto,Two-Door Car,537.600000

In [196]:
df_personal_corporate = df.loc[df['Policy Type'] == "Corporate Auto"]

df_personal_corporate

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
6,XZ87318,Oregon,F,College,538089.86%,55350.0,67.0,1/0/00,Corporate Auto,Four-Door Car,321.600000
7,CF85061,Arizona,M,Master,721610.03%,0.0,101.0,1/0/00,Corporate Auto,Four-Door Car,363.029680
8,DY87989,Oregon,M,Bachelor,2412750.40%,14072.0,71.0,1/0/00,Corporate Auto,Four-Door Car,511.200000
12,DP39365,California,NaN,Master,879879.70%,77026.0,110.0,1/2/00,Corporate Auto,Four-Door Car,472.029737
...,...,...,...,...,...,...,...,...,...,...,...
1045,WZ31900,Oregon,F,Bachelor,864970.06%,94389.0,107.0,1/0/00,Corporate Auto,SUV,85.063708
1050,BJ53923,Arizona,M,High School or Below,260027.21%,51978.0,66.0,1/0/00,Corporate Auto,Four-Door Car,144.782152
1052,FB23788,Oregon,M,High School or Below,882883.50%,86721.0,111.0,1/0/00,Corporate Auto,SUV,532.800000
1056,PI47776,Oregon,F,Bachelor,253070.51%,89451.0,63.0,1/0/00,Corporate Auto,Four-Door Car,61.769564
1059,YG44474,Oregon,M,College,1401472.13%,54193.0,117.0,1/0/00,Corporate Auto,SUV,720.752945

In [233]:
def media_valores(df, nombre_df:str, column, decimals):
    df_nombre = str(nombre_df)
    media = df[column].mean() # da muchos decimales
    media = round(float(media), decimals) # redondeo
    print(f"Media de {df_nombre} para el campo '{column}' = {media}")
    return media

In [234]:
media_valores_auto = media_valores(df_personal_auto, "Valores_Auto","Income",2)
media_valores_corporate = media_valores(df_personal_corporate,"Corporate_Auto","Income",2)

Media de Valores_Auto para el campo 'Income' = 38180.7
Media de Corporate_Auto para el campo 'Income' = 41390.31

### Bonus: Exercise 4

Your goal is to identify customers with a high policy claim amount.

Instructions:

- Review again the statistics for total claim amount to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount data.

*Note: When analyzing data, we often want to focus on certain groups of values to gain insights. Percentiles are a useful tool to help us define these groups. A percentile is a measure that tells us what percentage of values in a dataset are below a certain value. For example, the 75th percentile represents the value below which 75% of the data falls. Similarly, the 25th percentile represents the value below which 25% of the data falls. When we talk about the top 25%, we are referring to the values that fall above the 75th percentile, which represent the top quarter of the data. On the other hand, when we talk about the bottom 25%, we are referring to the values that fall below the 25th percentile, which represent the bottom quarter of the data. By focusing on these groups, we can identify patterns and trends that may be useful for making decisions and taking action.*

*Hint: look for a method that gives you the percentile or quantile 0.75 and 0.25 for a Pandas Series.*

*Hint 2: check `Boolean selection according to the values of a single column` in https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9*

In [ ]:
import pandas as pd
url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"
df = pd.read_csv(url)

In [258]:
def percentiles(df, column):
    q1 = df[column].quantile(0.25) #viene de quartil 1
    q2 = df[column].quantile(0.50)
    q3 = df[column].quantile(0.75)

    bottom_25 = df[df[column] < q1]
    top_75 = df[df[column] > q3]

    return q1,q2,q3, bottom_25, top_75

In [257]:
q1, q2, q3, bottom_25, top_75 = percentiles(df, "Income"); # le meto esto para que no me imprima la salida
print(f"top_75, {top_75}")

top_75,     Customer          ST GENDER             Education Customer Lifetime Value  \
13   SJ95423     Arizona    NaN  High School or Below              881901.89%
114  SG20925  Washington      F                Master              518579.76%
138  SX26335      Oregon    NaN               College              955292.69%
186  UF46533  California      F               College              457452.41%
219  CO44221        Cali      M               College              292991.65%
290  JT52858      Oregon      F              Bachelor              902786.72%
423  RE81445      Oregon      F               College              573459.82%
532  JS42382      Oregon   Male                Master              617291.42%
869  ER19995  Washington      F               College             1778627.78%
924  QJ40732     Arizona      M               College              488033.96%
932  ST43550      Oregon      M              Bachelor              572732.71%

      Income  Monthly Premium Auto Number of Open Complaints     Policy Type  \
13   99845.0                 110.0                    1/1/00  Corporate Auto
114  99428.0                6464.0                    1/1/00   Personal Auto
138  97732.0                  79.0                    1/0/00   Personal Auto
186  99316.0                 114.0                    1/0/00  Corporate Auto
219  98473.0                  72.0                    1/0/00   Personal Auto
290  99002.0                 112.0                    1/1/00   Personal Auto
423  98132.0                  71.0                    1/0/00   Personal Auto
532  99960.0                  76.0                    1/0/00  Corporate Auto
869  99790.0                6464.0                    1/0/00   Personal Auto
924  97984.0                  61.0                    1/1/00   Personal Auto
932  99934.0                  71.0                    1/0/00    Special Auto

     Vehicle Class  Total Claim Amount
13             SUV          528.000000
114  Four-Door Car           48.046869
138  Four-Door Car          289.912200
186            SUV          754.358929
219  Four-Door Car          345.600000
290  Four-Door Car          537.600000
423   Two-Door Car           50.587035
532  Four-Door Car          364.800000
869  Four-Door Car          178.986788
924  Four-Door Car          407.450118
932  Four-Door Car          460.323855