# Lab | Pandas

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

The data includes information such as customer ID, state, gender, education, income, and other variables that can be used to perform various analyses.

Throughout the lab, we will be using the pandas library in Python to manipulate and analyze the data. Pandas is a powerful library that provides various data manipulation and analysis tools, including the ability to load and manipulate data from a variety of sources, including CSV files.

### Data Description

- Customer - Customer ID

- ST - State where customers live

- Gender - Gender of the customer

- Education - Background education of customers 

- Customer Lifetime Value - Customer lifetime value(CLV) is the total revenue the client will derive from their entire relationship with a customer. In other words, is the predicted or calculated value of a customer over their entire duration as a policyholder with the insurance company. It is an estimation of the net profit that the insurance company expects to generate from a customer throughout their relationship with the company. Customer Lifetime Value takes into account factors such as the duration of the customer's policy, premium payments, claim history, renewal likelihood, and potential additional services or products the customer may purchase. It helps insurers assess the long-term profitability and value associated with retaining a particular customer.

- Income - Customers income

- Monthly Premium Auto - Amount of money the customer pays on a monthly basis as a premium for their auto insurance coverage. It represents the recurring cost that the insured person must pay to maintain their insurance policy and receive coverage for potential damages, accidents, or other covered events related to their vehicle.

- Number of Open Complaints - Number of complaints the customer opened

- Policy Type - There are three type of policies in car insurance (Corporate Auto, Personal Auto, and Special Auto)

- Vehicle Class - Type of vehicle classes that customers have Two-Door Car, Four-Door Car SUV, Luxury SUV, Sports Car, and Luxury Car

- Total Claim Amount - the sum of all claims made by the customer. It represents the total monetary value of all approved claims for incidents such as accidents, theft, vandalism, or other covered events.

External Resources: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

## Challenge 1: Understanding the data

In this challenge, you will use pandas to explore a given dataset. Your task is to gain a deep understanding of the data by analyzing its characteristics, dimensions, and statistical properties.

- Identify the dimensions of the dataset by determining the number of rows and columns it contains.
- Determine the data types of each column and evaluate whether they are appropriate for the nature of the variable. You should also provide suggestions for fixing any incorrect data types.
- Identify the number of unique values for each column and determine which columns appear to be categorical. You should also describe the unique values of each categorical column and the range of values for numerical columns, and give your insights.
- Compute summary statistics such as mean, median, mode, standard deviation, and quartiles to understand the central tendency and distribution of the data for numerical columns. You should also provide your conclusions based on these summary statistics.
- Compute summary statistics for categorical columns and providing your conclusions based on these statistics.

In [55]:
import pandas as pd
url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"
df = pd.read_csv(url)
df.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

- Identify the dimensions of the dataset by determining the number of rows and columns it contains.

In [56]:
def df_dimensions(df, show=True):
    filas, columnas = df.shape
    if show:
        print(f"Filas: {filas}, Columnas: {columnas}")
    return filas, columnas

df_dimensions(df);

Filas: 4008, Columnas: 11

- Determine the data types of each column and evaluate whether they are appropriate for the nature of the variable.

In [57]:
def df_types(df, show=True):
    tipos = df.dtypes
    if show:
        for col, t in tipos.items():
            print(f"{col}: {t}")
    return tipos

df_types(df);

Customer: str
ST: str
GENDER: str
Education: str
Customer Lifetime Value: str
Income: float64
Monthly Premium Auto: float64
Number of Open Complaints: str
Policy Type: str
Vehicle Class: str
Total Claim Amount: float64

 You should also provide suggestions for fixing any incorrect data types.

EVALUCION: 
customer es un ID esta bien str  
SE,GENDER,Education  es category --> ok  
Income , Monthly Premium Auto  --> float --> ok  
Customer Lifetime Value tiene % --> deberia ser float  
Number of Open Complaints tiene formato raro --> deberia ser int  
Policy Type , Vehicle Class --> str ok  
Total Claim Amount --> float ok

- Identify the number of unique values for each column

In [152]:
def df_unique_values(df, show=True):
    uniques = df.nunique()
    if show:
        print("Valores únicos por columna:")
        print(uniques)
    return uniques

df_unique_values(df);

Valores únicos por columna:
Customer                     1071
ST                              8
GENDER                          5
Education                       6
Customer Lifetime Value      1027
Income                        774
Monthly Premium Auto          132
Number of Open Complaints       6
Policy Type                     3
Vehicle Class                   6
Total Claim Amount            761
dtype: int64

determine which columns appear to be categorical.

In [147]:
cat_cols = df.select_dtypes(include=['object', 'string', 'category']).columns.tolist()
num_cols = df.select_dtypes(include='number').columns.tolist()

print("Columnas categóricas:", cat_cols)
print("Columnas numéricas:", num_cols)

Columnas categóricas: ['Customer', 'ST', 'GENDER', 'Education', 'Customer Lifetime Value', 'Number of Open Complaints', 'Policy Type', 'Vehicle Class']
Columnas numéricas: ['Income', 'Monthly Premium Auto', 'Total Claim Amount']

You should also describe the unique values of each categorical column and the range of values for numerical columns, and give your insights.

In [ ]:

def df_unique_values_column(df, columns, show=True, show_values=False):
    df_sub = df[columns]
    uniques = df_sub.nunique()

    if show:
        print("Valores únicos por columna:")
        print(uniques)

    if show_values:
        for col in columns:
            print(f"\n--- {col} ---")
            print(df[col].unique())

    return uniques

unique_values_category = df_unique_values_column(df, cat_cols, True)
unique_values_category;

Valores únicos por columna:
Customer                     1071
ST                              8
GENDER                          5
Education                       6
Customer Lifetime Value      1027
Number of Open Complaints       6
Policy Type                     3
Vehicle Class                   6
dtype: int64

In [165]:
for col in num_cols:
    col_min = df[col].min()
    col_max = df[col].max()
    print(f"{col}: min={col_min}, max={col_max}, rango={col_max - col_min}")

Income: min=0.0, max=99960.0, rango=99960.0
Monthly Premium Auto: min=61.0, max=35354.0, rango=35293.0
Total Claim Amount: min=0.382107, max=2893.239678, rango=2892.857571

Insights : qué columnas parecen claramente categóricas, cuáles tienen pocos valores distintos y qué te dice el rango de variables como Income o Total Claim Amount sobre la dispersión.

- Compute summary statistics such as mean, median, mode, standard deviation, and quartiles to understand the central tendency and distribution of the data for numerical columns. You should also provide your conclusions based on these summary statistics.

In [89]:


num_cols =df.select_dtypes(include='number').columns.tolist()

summary_stats = pd.DataFrame({
    'mean':df[num_cols].mean(),
    'median':df[num_cols].median(),
    'mode':df[num_cols].mode().iloc[0],
    'std':df[num_cols].std(),
    'q1':df[num_cols].quantile(0.25),
    'q3':df[num_cols].quantile(0.75)
})

summary_stats['iqr'] = summary_stats['q3'] - summary_stats['q1']
summary_stats

,mean,median,mode,std,q1,q3,iqr
Income,39295.701214,36234.000000,0.0,30469.427060,14072.000000,64631.0,50559.000000
Monthly Premium Auto,193.234360,83.000000,65.0,1601.190369,68.000000,109.5,41.500000
Total Claim Amount,404.986909,354.729129,321.6,293.027260,202.157702,532.8,330.642298

- Compute summary statistics for categorical columns and providing your conclusions based on these statistics.

In [91]:
cat_summary = df[cat_cols].describe().T
cat_summary

                          count unique            top freq
Customer                   1071   1071        RB50392    1
ST                         1071      8         Oregon  320
GENDER                      954      5              F  457
Education                  1071      6       Bachelor  324
Customer Lifetime Value    1068   1027     445811.34%    4
Number of Open Complaints  1071      6         1/0/00  830
Policy Type                1071      3  Personal Auto  780
Vehicle Class              1071      6  Four-Door Car  576

## Challenge 2: analyzing the data

### Exercise 1

The marketing team wants to know the top 5 less common customer locations. Create a pandas Series object that contains the customer locations and their frequencies, and then retrieve the top 5 less common locations in ascending order.

In [110]:
import pandas as pd
url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"
df = pd.read_csv(url)
df.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

Create a pandas Series object that contains the customer locations and their frequencies

In [168]:
location_counts = df['ST'].value_counts()
ordered_ascending_order = location_counts.sort_values(ascending=True)
less_common_locations = ordered_ascending_order.head(5)
print(f"Serie de frecuencias de unicacion : {less_common_locations} ")

Serie de frecuencias de unicacion : ST
AZ             25
WA             30
Washington     81
Nevada         98
Cali          120
Name: count, dtype: int64

### Exercise 2

The sales team wants to know the total number of policies sold for each type of policy. Create a pandas Series object that contains the policy types and their total number of policies sold, and then retrieve the policy type with the highest number of policies sold.

*Hint:*
- *Using value_counts() method simplifies this analysis.*
- *Futhermore, there is a method that returns the index of the maximum value in a column or row.*

In [66]:
import pandas as pd
url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"
df = pd.read_csv(url)
df.head()
df.describe(include= "all")

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
count,1071,1071,954,1071,1068,1071.000000,1071.000000,1071,1071,1071,1071.000000
unique,1071,8,5,6,1027,NaN,NaN,6,3,6,NaN
top,RB50392,Oregon,F,Bachelor,445811.34%,NaN,NaN,1/0/00,Personal Auto,Four-Door Car,NaN
freq,1,320,457,324,4,NaN,NaN,830,780,576,NaN
mean,NaN,NaN,NaN,NaN,NaN,39295.701214,193.234360,NaN,NaN,NaN,404.986909
std,NaN,NaN,NaN,NaN,NaN,30469.427060,1601.190369,NaN,NaN,NaN,293.027260
min,NaN,NaN,NaN,NaN,NaN,0.000000,61.000000,NaN,NaN,NaN,0.382107
25%,NaN,NaN,NaN,NaN,NaN,14072.000000,68.000000,NaN,NaN,NaN,202.157702
50%,NaN,NaN,NaN,NaN,NaN,36234.000000,83.000000,NaN,NaN,NaN,354.729129
75%,NaN,NaN,NaN,NaN,NaN,64631.000000,109.500000,NaN,NaN,NaN,532.800000
max,NaN,NaN,NaN,NaN,NaN,99960.000000,35354.000000,NaN,NaN,NaN,2893.239678

The sales team wants to know the total number of policies sold for each type of policy.  
 Create a pandas Series object that contains the policy types and their total number of policies sold,

and then retrieve the policy type with the highest number of policies sold.

In [170]:
policy_counts = df["Policy Type"].value_counts()
print(policy_counts)

Policy Type
Personal Auto     780
Corporate Auto    234
Special Auto       57
Name: count, dtype: int64

In [172]:
policy_type = policy_counts.idxmax()
print(f"Highest number: {policy_type}")

Highest number: Personal Auto

### Exercise 3

The sales team wants to know if customers with Personal Auto have a lower income than those with Corporate Auto. How does the average income compare between the two policy types?

- Use *loc* to create two dataframes: one containing only Personal Auto policies and one containing only Corporate Auto policies.
- Calculate the average income for each policy.
- Print the results.

In [73]:
import pandas as pd
url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"
df = pd.read_csv(url)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   1071 non-null   str
 1   ST                         1071 non-null   str
 2   GENDER                     954 non-null    str
 3   Education                  1071 non-null   str
 4   Customer Lifetime Value    1068 non-null   str
 5   Income                     1071 non-null   float64
 6   Monthly Premium Auto       1071 non-null   float64
 7   Number of Open Complaints  1071 non-null   str
 8   Policy Type                1071 non-null   str
 9   Vehicle Class              1071 non-null   str
 10  Total Claim Amount         1071 non-null   float64
dtypes: float64(3), str(8)
memory usage: 344.6 KB

In [135]:
df_personal = df.loc[df["Policy Type"] == "Personal Auto"]

df_personal.head(5)

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
5,OC83172,Oregon,F,Bachelor,825629.78%,62902.0,69.0,1/0/00,Personal Auto,Two-Door Car,159.383042

- Calculate the average income for each policy.

In [134]:
df_corporate = df.loc[df["Policy Type"] == "Corporate Auto"]

df_corporate.head(5)

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
6,XZ87318,Oregon,F,College,538089.86%,55350.0,67.0,1/0/00,Corporate Auto,Four-Door Car,321.600000
7,CF85061,Arizona,M,Master,721610.03%,0.0,101.0,1/0/00,Corporate Auto,Four-Door Car,363.029680
8,DY87989,Oregon,M,Bachelor,2412750.40%,14072.0,71.0,1/0/00,Corporate Auto,Four-Door Car,511.200000
12,DP39365,California,NaN,Master,879879.70%,77026.0,110.0,1/2/00,Corporate Auto,Four-Door Car,472.029737

In [ ]:
avg_income_personal = df_personal["Income"].mean()
avg_income_corporate = df_corporate["Income"].mean()
def compare_income():
    if avg_income_personal < avg_income_corporate:
        resultado = "avg income personal es MAYOR que avg income corporate"
    elif avg_income_personal < avg_income_corporate:
        resultado = "avg income corporate es MAYOR que avg income personal"
    else: 
        resultado = " avg income es el mismo en peronay y corporate"
    print("Average income for Personal Auto policies:", avg_income_personal)
    print("Average income for Corporate Auto policies:", avg_income_corporate)
    return resultado

- Print the results.

In [176]:

resultado_comparacion = compare_income()
print(resultado_comparacion)

Average income for Personal Auto policies: 38180.69871794872
Average income for Corporate Auto policies: 41390.31196581197
avg income personal es MAYOR que avg income corporate

### Bonus: Exercise 4

Your goal is to identify customers with a high policy claim amount.

Instructions:

- Review again the statistics for total claim amount to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount data.

*Note: When analyzing data, we often want to focus on certain groups of values to gain insights. Percentiles are a useful tool to help us define these groups. A percentile is a measure that tells us what percentage of values in a dataset are below a certain value. For example, the 75th percentile represents the value below which 75% of the data falls. Similarly, the 25th percentile represents the value below which 25% of the data falls. When we talk about the top 25%, we are referring to the values that fall above the 75th percentile, which represent the top quarter of the data. On the other hand, when we talk about the bottom 25%, we are referring to the values that fall below the 25th percentile, which represent the bottom quarter of the data. By focusing on these groups, we can identify patterns and trends that may be useful for making decisions and taking action.*

*Hint: look for a method that gives you the percentile or quantile 0.75 and 0.25 for a Pandas Series.*

*Hint 2: check `Boolean selection according to the values of a single column` in https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9*

In [78]:
import pandas as pd
url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv"
df = pd.read_csv(url)

In [137]:
df['Total Claim Amount'].describe()

count    1071.000000
mean      404.986909
std       293.027260
min         0.382107
25%       202.157702
50%       354.729129
75%       532.800000
max      2893.239678
Name: Total Claim Amount, dtype: float64

In [138]:
q75 = df['Total Claim Amount'].quantile(0.75)
q75

np.float64(532.8)

In [139]:
df_high_claim = df.loc[df['Total Claim Amount'] > q75]
df_high_claim.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
17,OE15005,Cali,NaN,College,394524.16%,28855.0,101.0,1/0/00,Personal Auto,SUV,647.442031
23,TZ98966,Nevada,NaN,Bachelor,245019.10%,0.0,73.0,1/3/00,Corporate Auto,Four-Door Car,554.376763
26,US89481,California,NaN,Bachelor,394637.21%,0.0,111.0,1/0/00,Personal Auto,Four-Door Car,799.200000

In [178]:
high_claim_stats = df_high_claim['Total Claim Amount'].describe()
print(f"high_claim_stats: \n{high_claim_stats}")

high_claim_stats:
count     264.000000
mean      782.228263
std       292.751640
min       537.600000
25%       606.521741
50%       679.597985
75%       851.400000
max      2893.239678
Name: Total Claim Amount, dtype: float64